from typing import List
from datetime import datetime
from beanie import Document, Link
from pydantic import Field
from app.models.user import User

class LearningMemory(Document):
    """
    Long-term summaries and insights about a learner's journey.
    Generated by background jobs that analyze patterns across multiple reviews.
    """
    user: Link[User]
    
    # Aggregated insights
    summary: str  # Natural language summary of progress
    timeframe: str  # e.g., "week_2024_06", "month_2024_02"
    
    # Topics and patterns
    topics_covered: List[str] = Field(default_factory=list)
    progress_trend: str  # "improving", "stagnant", "regressing"
    
    # Key moments
    key_breakthroughs: List[str] = Field(default_factory=list)  # Major progress moments
    persistent_struggles: List[str] = Field(default_factory=list)  # Recurring issues
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.now)
    num_reviews_analyzed: int = 0
    
    class Settings:
        name = "learning_memories"
        
    class Config:
        json_schema_extra = {
            "example": {
                "summary": "Strong improvement in array manipulation. Still struggling with dynamic programming concepts.",
                "timeframe": "week_2024_06",
                "topics_covered": ["arrays", "hash_maps", "two_pointers"],
                "progress_trend": "improving",
                "key_breakthroughs": ["Mastered hash table optimization"],
                "persistent_struggles": ["Bottom-up DP recursion"]
            }
        }
